replicaCount: 2

image:
  repository: harshit1105/my-image-1
  tag: "12597326493"
  pullPolicy: IfNotPresent

podLabels:
  app: pvc-pod

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: pvc-pod-service
