name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Hss/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Generate Version
        id: version
        run: |
          # Start with v1 and increment based on commit count
          VERSION="v$(git rev-list --count HEAD)"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: ./Python_App/
          file: ./Python_App/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-image-1:${{github.run_id}}

  update-newtag-in-helm-chart:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm_gke/python_app_dm/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "harshitsan@gmail.com"
          git config --global user.name "harshit1105"
          git add helm_gke/python_app_dm/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
