name: Push Docker Image to Artifactory

on:
  push:
    paths:
      - 'Hss/test/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  
      
    - name: Authenticate to GCP using Workload Identity Federation
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/46134322728/locations/global/workloadIdentityPools/ghaaction/providers/github"
        service_account: "gha-466@kinetic-dogfish-446616-r8.iam.gserviceaccount.com"
        
    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/kinetic-dogfish-446616-r8/simple-application/my-image:${{github.run_id}} ci_python_app/

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/kinetic-dogfish-446616-r8/simple-application/my-image:${{github.run_id}}

  update-newtag-in-deployment:
    runs-on: ubuntu-latest
      
    needs: build-and-push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in deployment
      run: |
        sed -i '/image:/s/\(:[^:]*:\)[^:]*$/\${{github.run_id}}/' GKE_Argocd_Deployment/deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "harshitsan@gmail.com"
        git config --global user.name "harshit1105"
        git add GKE_Argocd_Deployment/deployment.yaml
        git commit -m "Update tag in Deployment"
        git push
